### ISSUE TITLE
หน้า Staff ไม่รองรับ Responsive

### ISSUE THREAD

**Issue by themes12** [themes12/itechgrad#5]
For example.
![image](https://github.com/themes12/itechgrad/assets/32432714/977f1f01-0ac4-4df1-99c3-97251509becc)

**Comment by pattamatha** [comment]
ฝ้ายกำลังทำอยู่ กำลังลองนะ

**Comment by pattamatha** [comment]
ยังไม่เสร็จ ใครจะต่อ pull ลงมาได้เลย

**Comment by themes12** [comment]
now, i think its ok.
