### ISSUE TITLE
Bug หน้า Admin PhD 

### ISSUE THREAD

**Issue by phanukorn222** [themes12/itechgrad#7]
-อยู่หน้าจัดการของPhD
![image](https://github.com/themes12/itechgrad/assets/118677350/d2aac205-ed1f-4d63-9c46-5efb73682073)
-กดเพิ่มรายวิชาแล้วไปเข้าของ master's degree
![image](https://github.com/themes12/itechgrad/assets/118677350/6c9eeefe-e91f-41e4-baa0-5064fb4174a8)
-เมื่อทำการกดกลับไปหน้าจัดการโดยการกดที่ [ จัดการ Course ] กลายเป็นเข้าจัดการของmaster's degree แทนที่จะเป็น PhD 
-ข้อมูลที่เพิ่มไปก็ไปขึ้นของmaster's degree 
![image](https://github.com/themes12/itechgrad/assets/118677350/76ebeb5c-3bdc-4ede-b681-05fcc650f678)
-เมื่อทำการกดปุ่มDisplay ข้อมูลไปขึ่้นที่ Master's degree courses
![image](https://github.com/themes12/itechgrad/assets/118677350/d3e7bfc8-4774-42a0-9a01-5f45fe0beb02)

**Comment by themes12** [comment]
It should be fixed by now.

**Comment by themes12** [comment]
Fixed
